title: Seda 的個人網站
email: your@email.com
description: >-
  SEO內容寫作者、網站優化實作者。這裡是我的筆記與作品空間。

twitter_username: ""
github_username: sedagit
minimal_mistakes_skin: default
search: true

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: Asia/Taipei

include:
  - _pages

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

# ✅ 導覽列設定
navigation:
  - title: 首頁
    url: /
  - title: 作品集
    url: /projects/
  - title: 部落格
    url: /blog/
  - title: 關於我
    url: /about/

# ✅ 作者資訊
author:
  name   : "Seda"
  avatar : "/assets/images/bio-photo.jpg" # 可改成你自己的圖片網址
  bio    : "SEO內容創作者，熱愛策略與實作"
  location: Taiwan
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sedagit"
    - label: "網站"
      icon: "fas fa-fw fa-link"
      url: "https://sedagit.github.io"

# ✅ 頁尾連結
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/sedagit"

# 預設佈局設定
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
